/**
 * Adopted from https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types.
 *
 * A mapping of file extensions to common MIME types.
 */
export enum CommonMIMETypes {
  AAC = "audio/aac",
  ABW = "application/x-abiword",
  ARC = "application/x-freearc",
  AVIF = "image/avif",
  AVI = "video/x-msvideo",
  BIN = "application/octet-stream",
  BMP = "image/bmp",
  BZ = "application/x-bzip",
  BZ2 = "application/x-bzip2",
  CDA = "application/x-cdf",
  CSH = "application/x-csh",
  CSS = "text/css",
  CSV = "text/csv",
  DOC = "application/msword",
  DOCX =
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  EOT = "application/vnd.ms-fontobject",
  EPUB = "application/epub+zip",
  GZ = "application/gzip",
  GIF = "image/gif",
  HTML = "text/html",
  ICO = "image/vnd.microsoft.icon",
  ICS = "text/calendar",
  JAR = "application/java-archive",
  JPG = "image/jpeg",
  JPEG = "image/jpeg",
  JS = "text/javascript",
  JSON = "application/json",
  JSONLD = "application/ld+json",
  MID = "audio/midi",
  MIDI = "audio/midi",
  MJS = "text/javascript",
  MP3 = "audio/mpeg",
  MP4 = "video/mp4",
  MPEG = "video/mpeg",
  MPKG = "application/vnd.apple.installer+xml",
  ODP = "application/vnd.oasis.opendocument.presentation",
  ODS = "application/vnd.oasis.opendocument.spreadsheet",
  ODT = "application/vnd.oasis.opendocument.text",
  OGA = "audio/ogg",
  OGV = "video/ogg",
  OGX = "application/ogg",
  OPUS = "audio/opus",
  OTF = "font/otf",
  PNG = "image/png",
  PDF = "application/pdf",
  PHP = "application/x-httpd-php",
  PPT = "application/vnd.ms-powerpoint",
  PPTX =
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  RAR = "application/vnd.rar",
  RTF = "application/rtf",
  SH = "application/x-sh",
  SVG = "image/svg+xml",
  TAR = "application/x-tar",
  TIF = "image/tiff",
  TIFF = "image/tiff",
  TS = "video/mp2t",
  TTF = "font/ttf",
  TXT = "text/plain",
  VSD = "application/vnd.visio",
  WAV = "audio/wav",
  WEBA = "audio/webm",
  WEBM = "video/webm",
  WEBP = "image/webp",
  WOFF = "font/woff",
  WOFF2 = "font/woff2",
  XHTML = "application/xhtml+xml",
  XLS = "application/vnd.ms-excel",
  XLSX = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  XML = "application/xml",
  XUL = "application/vnd.mozilla.xul+xml",
  ZIP = "application/zip",
  // 3gp and 3g2 are ignored from the MDN webpage.
  "7Z" = "application/x-7z-compressed",
}
